# -*- coding: utf-8 -*-
"""Card price list extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2K7SPE56eO1YlX4bVHIXBL4slDCKgmb
"""

!pip install opencv-python pillow matplotlib tqdm pandas openpyxl -q

"""Import"""

import zipfile
import cv2
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path
from tqdm import tqdm
from PIL import Image
from google.colab import files

"""Upload Zip"""

uploaded = files.upload()

"""Extract Zip"""

import shutil

zip_name = list(uploaded.keys())[0]

extract_folder = Path("/content/images")
# Clear the folder before extracting new files to ensure only the latest upload is processed
if extract_folder.exists() and extract_folder.is_dir():
    shutil.rmtree(extract_folder)
extract_folder.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(zip_name,"r") as zip_ref:
    zip_ref.extractall(extract_folder)

image_files = []

for ext in ["*.jpg","*.jpeg","*.png","*.JPG","*.JPEG"]:

    image_files.extend(
        extract_folder.rglob(ext)
    )

image_files = sorted(image_files)

print("Jumlah gambar :",len(image_files))

"""Data Preprocessing"""

processed_folder = Path("/content/preprocessed")
processed_folder.mkdir(exist_ok=True)

processed_images = []

for img_path in tqdm(image_files):

    img = cv2.imread(str(img_path))

    h,w = img.shape[:2]

    if w>1800:

        scale = 1800/w

        img = cv2.resize(
            img,
            (1800,int(h*scale))
        )

    lab = cv2.cvtColor(img,cv2.COLOR_BGR2LAB)

    l,a,b = cv2.split(lab)

    clahe = cv2.createCLAHE(
        clipLimit=2.0,
        tileGridSize=(8,8)
    )

    l = clahe.apply(l)

    lab = cv2.merge((l,a,b))

    img = cv2.cvtColor(
        lab,
        cv2.COLOR_LAB2BGR
    )

    kernel=np.array([
        [0,-1,0],
        [-1,5,-1],
        [0,-1,0]
    ])

    img=cv2.filter2D(img,-1,kernel)

    save_path = processed_folder/img_path.name

    cv2.imwrite(str(save_path),img)

    processed_images.append(save_path)

print("Preprocessing selesai")

"""Setup Gemini"""

from google import genai
from google.genai import types
from google.colab import userdata
import itertools

# Ambil API Key dari daftar yang disediakan
API_KEYS = [
    "YOUR_API_KEY_1",
    "YOUR_API_KEY_2",
    "YOUR_API_KEY_3",
    "YOUR_API_KEY_4",
    "YOUR_API_KEY_5"
]

# Iterator untuk siklus API keys
api_key_iterator = itertools.cycle(API_KEYS)
# Global variable to hold the currently active client instance
client = None
MODEL = "gemini-1.5-flash"

def get_new_gemini_client():
    global client
    new_api_key = next(api_key_iterator)
    print(f"Attempting to use API key: {new_api_key[:5]}...{new_api_key[-5:]}")
    client = genai.Client(api_key=new_api_key)
    return client

# Initialize the client for the first time
client = get_new_gemini_client()
print(f"✅ Gemini Client Initialized (using first key)")

from PIL import Image
import json

# Ambil gambar pertama hasil preprocessing (bisa dilooping seperti script Anda sebelumnya)
image_path = processed_images[0]
img = Image.open(image_path)

PROMPT = """
You are an expert OCR and data extraction assistant for Indonesian cellular operators.
Your task is to extract EVERY internet package visible in this image into a JSON format.

Ignore: watermarks, shelves, bottles, reflections, human objects, posters unrelated to internet packages.

Return ONLY a valid JSON array of objects.

JSON format:
[
  {
    "provider": "IM3",
    "price": 0,
    "gb": 0.0,
    "days": 0
  }
]

CRITICAL RULES:
1. PROVIDER CODES: "TSEL", "IM3", "3ID", "XL", "AXIS", "SF".

2. CURRENCY CONVERSION:
   Convert "K" to thousands (e.g., 37K -> 37000). Ignore "Rp", ".", or spaces.

3. THE "UNLIMITED" MULTIPLICATION RULE (CRITICAL FOR "GB/hari"):
   - Scan the banner or the specific package section for the keyword "UNLIMITED".
   - IF IT IS AN "UNLIMITED" PACKAGE AND specifies a daily quota (e.g., 1, 1.5, 2, 3 "GB/hari") with an active period (e.g., "28 Hari"), you MUST multiply them to get the total GB. (Example: "3 GB/hari" for 28 Hari = 84.0 GB).
   - IF IT IS NOT AN "UNLIMITED" PACKAGE (regular packages), the text "GB/hari" is a TYPO from the print shop. DO NOT MULTIPLY. Just extract the exact base number written (e.g., treat "24 GB/hari" for 28 Hari as simply 24.0).

4. STRICT DATA TYPES:
   - "price" must be integer.
   - "gb" must be float or integer.
   - "days" must be integer.

5. MISSING DATA:
   If one row has missing Price OR GB OR Days, ignore that row. Do not guess incomplete data.

6. Output raw JSON only. Do not use markdown like ```json.
"""
try:
    response = client.models.generate_content(
        model=MODEL,
        contents=[
            PROMPT,
            img
        ]
    )

    # Membersihkan kemungkinan output markdown dari AI
    text = response.text.strip()
    text = text.replace("```json", "").replace("```", "")

    data = json.loads(text)
    print("✅ Berhasil mengekstrak data:")
    print(json.dumps(data[:3], indent=2)) # Print 3 baris pertama untuk preview
    print(f"... (total {len(data)} paket)")

except Exception as e:
    print("❌ Gagal Parse JSON")
    print(e)
    if 'response' in locals():
        print(response.text)

uploaded = files.upload()

import json
import time
import pandas as pd
from IPython.display import display
from PIL import Image

all_packages = []

for image_path in processed_images:

    print("="*80)
    print(f"📷 IMAGE : {image_path.stem}")
    print("="*80)

    img = Image.open(image_path)

    # Kita naikkan retries karena sekarang kita punya "amunisi" 5 API Key
    max_retries = 6

    for attempt in range(max_retries):
        try:
            # Menggunakan client yang sedang aktif
            response = client.models.generate_content(
                model=MODEL,
                contents=[
                    PROMPT,
                    img
                ]
            )

            text = response.text.strip()
            text = text.replace("```json", "").replace("```", "")
            data = json.loads(text)

            # simpan ke master
            all_packages.extend(data)

            # dataframe khusus image ini
            df_image = pd.DataFrame(data)
            display(df_image)
            print(f"✅ Total package : {len(df_image)}")

            # Jika berhasil, hentikan loop retry dan lanjut ke gambar berikutnya
            break

        except Exception as e:
            error_msg = str(e)

            # Deteksi error kuota habis (429) atau server sibuk (503)
            if "503" in error_msg or "UNAVAILABLE" in error_msg or "429" in error_msg:
                print(f"⚠️ API Limit / Server Sibuk (Attempt {attempt+1}/{max_retries}).")

                # Eksekusi perpindahan (oper) ke API Key berikutnya
                client = get_new_gemini_client()

                # Beri jeda 2 detik agar koneksi client baru stabil sebelum menembak API lagi
                time.sleep(2)
            else:
                print("❌ Gagal Parse JSON atau Error Lainnya")
                print(error_msg)
                if 'response' in locals():
                    print(response.text)
                break # Hentikan retry jika error-nya bukan karena kuota/server sibuk

"""Cell 9"""

import pandas as pd

df = pd.DataFrame(all_packages)

df["yield"] = df["price"]/df["gb"]

df

import pandas as pd

# Masukkan hasil JSON AI terbaru ke dalam DataFrame
df_clean = pd.DataFrame(all_packages)

# Konversi tipe data untuk memastikan format angka
df_clean['price'] = pd.to_numeric(df_clean['price'], errors='coerce')
df_clean['gb'] = pd.to_numeric(df_clean['gb'], errors='coerce')
df_clean['days'] = pd.to_numeric(df_clean['days'], errors='coerce')

# Buang baris yang kosong/gagal terekstrak
df_clean = df_clean.dropna(subset=['price', 'gb', 'days'])

print(f"✅ df_clean berhasil diperbarui dengan {len(df_clean)} paket dari AI terbaru.")

import pandas as pd
import numpy as np
import re

print("Membaca dan memproses data evaluasi...")

# 1. Load Data Manual (Ground Truth)
# Melewati 3 baris pertama karena header asli ada di baris ke-4
df_gt_raw = pd.read_csv("datatest_Pricelistt - Sheet1.csv", skiprows=3)
df_gt = df_gt_raw.dropna(subset=['Provider', 'Price']).copy()

# 2. Cleansing Data Manual (Antisipasi Typo Manusia)
provider_mapping_gt = {
    'INDOSAT': 'IM3', 'THREE': '3ID', 'TELKOMSEL': 'TSEL',
    'SMARTFREN': 'SF', 'XL': 'XL', 'AXIS': 'AXIS', '3': '3ID'
}
df_gt['provider_clean'] = df_gt['Provider'].astype(str).str.strip().str.upper().map(provider_mapping_gt).fillna(df_gt['Provider'].astype(str).str.strip().str.upper())

def extract_number(val, is_float=False):
    s = str(val).lower().replace('rp', '').replace(' ', '')
    if is_float:
        # Untuk GB (Float): Ubah koma jadi titik, tapi jangan hapus titik yang sudah ada
        s = s.replace(',', '.')
        s = re.sub(r'[^\d.]', '', s)
        return float(s) if s else 0.0
    else:
        # Untuk Harga (Integer): Hapus titik ribuan
        s = s.replace('.', '')
        s = re.sub(r'[^\d]', '', s)
        return int(s) if s else 0

df_gt['gb_clean'] = df_gt['GB'].apply(lambda x: extract_number(x, is_float=True))
df_gt['price_clean'] = df_gt['Price'].apply(lambda x: extract_number(x, is_float=False))
df_gt['days_clean'] = pd.to_numeric(df_gt['Days'], errors='coerce').fillna(0).astype(int)

# Fungsi membuat ID unik per baris
def make_key(prov, gb, days, price):
    # Menyederhanakan float misal 5.0 dan 5 akan sama-sama menjadi string '5.0'
    return f"{prov}_{float(gb)}_{int(days)}_{int(price)}"

df_gt['match_key'] = df_gt.apply(lambda row: make_key(row['provider_clean'], row['gb_clean'], row['days_clean'], row['price_clean']), axis=1)

# 3. Matching dengan Prediksi AI
if 'df_clean' not in locals():
    print("Variabel df_clean belum ada. Harap jalankan script pembuatan df_clean sebelumnya.")
else:
    df_pred = df_clean.copy()
    df_pred['match_key'] = df_pred.apply(lambda row: make_key(row['provider'], row['gb'], row['days'], row['price']), axis=1)

    gt_counts = df_gt['match_key'].value_counts().to_dict()
    pred_counts = df_pred['match_key'].value_counts().to_dict()

    all_keys = set(gt_counts.keys()).union(set(pred_counts.keys()))
    matched_total = 0; missed_keys = []; over_keys = []

    for k in all_keys:
        c_gt = gt_counts.get(k, 0)
        c_pred = pred_counts.get(k, 0)

        match_count = min(c_gt, c_pred)
        matched_total += match_count

        if c_gt > c_pred: missed_keys.extend([k] * (c_gt - c_pred))
        if c_pred > c_gt: over_keys.extend([k] * (c_pred - c_gt))

    # 4. Cetak Laporan
    acc = (matched_total / len(df_gt)) * 100 if len(df_gt) > 0 else 0
    print("\n" + "="*65)
    print("📊 LAPORAN EVALUASI AKURASI: AI vs ADMIN MANUAL")
    print("="*65)
    print(f"Total Data Manual (Ground Truth) : {len(df_gt)} paket")
    print(f"Total Data Ekstraksi AI          : {len(df_pred)} paket")
    print(f"Total Cocok Sempurna (Matched)   : {matched_total} paket")
    print(f"AKURASI AI                    : {acc:.2f} %")
    print("="*65)

    if missed_keys:
        print(f"\n❌ DATA MISSED ({len(missed_keys)} paket) -> Ada di manual, tapi beda/gagal di AI:")
        display(pd.DataFrame([k.split('_') for k in missed_keys], columns=['Provider', 'GB', 'Hari', 'Harga']))

    if over_keys:
        print(f"\n⚠️ OVER-EXTRACTED ({len(over_keys)} paket) -> Ditangkap AI, tapi tidak ada di Manual:")
        display(pd.DataFrame([k.split('_') for k in over_keys], columns=['Provider', 'GB', 'Hari', 'Harga']))

import pandas as pd
import numpy as np
import math
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.utils import get_column_letter
from google.colab import files

# --- 1. CLEANING & PREPARATION ---
# Karena kolom 'package_name' sudah dihapus dari prompt AI, kita langsung copy dataframe-nya
df_clean = df.copy()

# Normalisasi Provider
provider_mapping = {
    'INDOSAT': 'IM3', 'THREE': '3ID', 'TELKOMSEL': 'TSEL',
    'SMARTFREN': 'SF', 'XL': 'XL', 'AXIS': 'AXIS'
}
# ... (lanjutkan dengan kode Anda yang ada di bawahnya)
df_clean['provider'] = df_clean['provider'].astype(str).str.upper().map(provider_mapping).fillna(df_clean['provider'].astype(str).str.upper())

# Konversi tipe data dan kalkulasi Yield
df_clean['price'] = pd.to_numeric(df_clean['price'], errors='coerce')
df_clean['gb'] = pd.to_numeric(df_clean['gb'], errors='coerce')
df_clean['days'] = pd.to_numeric(df_clean['days'], errors='coerce')
df_clean = df_clean.dropna(subset=['price', 'gb', 'days']) # Buang data tidak lengkap

df_clean['yield'] = (df_clean['price'] / df_clean['gb']).apply(lambda x: math.ceil(x) if x != np.inf else 0)

# Kategorisasi
def categorize(d, p):
    if d <= 2: return "SACHET 1D-2D"
    elif d == 3: return "SACHET 3D"
    elif d <= 5: return "SACHET 5D"
    elif d <= 7: return "SACHET 7D"
    elif d <= 15: return "SACHET 10D-15D"
    elif d >= 28 and p <= 50000: return "MONTHLY 30-50K"
    elif d >= 28 and p > 50000: return "MONTHLY > 50K"
    else: return "OTHER"

df_clean['category'] = df_clean.apply(lambda row: categorize(row['days'], row['price']), axis=1)

# Sortir data dari yang termurah per kategori
df_clean = df_clean.sort_values(by=['category', 'provider', 'price'])


# --- 2. EXCEL GENERATION (OPENPYXL) ---
wb = Workbook()
ws = wb.active
ws.title = "Rekap Harga Automasi"

HEADER_COLORS = {"IM3": "FFC000", "3ID": "FF00FF", "TSEL": "FF0000", "XL": "0070C0", "AXIS": "7030A0", "SF": "FF00FF"}
providers_order = ["IM3", "3ID", "TSEL", "XL", "AXIS", "SF"]
categories_order = ["SACHET 1D-2D", "SACHET 3D", "SACHET 5D", "SACHET 7D", "SACHET 10D-15D", "MONTHLY 30-50K", "MONTHLY > 50K"]

font_bold_white = Font(bold=True, color="FFFFFF")
align_center = Alignment(horizontal="center", vertical="center")
border_thin = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))
border_red_dashed = Border(left=Side(style='mediumDashed', color='FF0000'), right=Side(style='mediumDashed', color='FF0000'),
                           top=Side(style='mediumDashed', color='FF0000'), bottom=Side(style='mediumDashed', color='FF0000'))

# Generate Header
col_start = 2
for prov in providers_order:
    ws.merge_cells(start_row=1, start_column=col_start, end_row=1, end_column=col_start+3)
    c = ws.cell(row=1, column=col_start, value=prov)
    c.fill, c.font, c.alignment, c.border = PatternFill(start_color=HEADER_COLORS.get(prov, "808080"), fill_type="solid"), font_bold_white, align_center, border_thin

    for i, sh in enumerate(["Price", "GB", "Days", "Yield"]):
        c_sub = ws.cell(row=2, column=col_start+i, value=sh)
        c_sub.fill = PatternFill(start_color="FFD966", fill_type="solid") if sh == "Yield" else PatternFill(start_color="D9D9D9", fill_type="solid")
        c_sub.font, c_sub.alignment, c_sub.border = Font(bold=True), align_center, border_thin
    col_start += 4

# Generate Body Data Horizontal
current_row = 3
yield_cells = [] # Untuk menyimpan koordinat sel yang akan diberi warna heatmap (conditional formatting)

for cat in categories_order:
    cat_df = df_clean[df_clean['category'] == cat]
    if cat_df.empty: continue

    # Kelompokkan data per provider dalam bentuk list dictionary
    prov_data = {prov: cat_df[cat_df['provider'] == prov].to_dict('records') for prov in providers_order}
    max_rows = max([len(v) for v in prov_data.values()] + [1])

    # Merge sel Kategori
    ws.merge_cells(start_row=current_row, start_column=1, end_row=current_row+max_rows-1, end_column=1)
    c_cat = ws.cell(row=current_row, column=1, value=cat)
    c_cat.alignment, c_cat.border = Alignment(vertical="center", horizontal="center", wrap_text=True), border_thin

    # Isi Baris Data
    for i in range(max_rows):
        col_idx = 2

        # Cari yield terkecil di baris ini untuk "Best Offer Red Dashed Box"
        row_yields = []
        for prov in providers_order:
            if i < len(prov_data[prov]): row_yields.append(prov_data[prov][i]['yield'])
        min_yield_in_row = min(row_yields) if row_yields else None

        for prov in providers_order:
            for offset in range(4): # Set border abu-abu default untuk semua sel (meskipun kosong)
                ws.cell(row=current_row+i, column=col_idx+offset).border = border_thin

            if i < len(prov_data[prov]):
                pkg = prov_data[prov][i]

                # Format Harga & Yield (Rp / Koma Ribuan)
                ws.cell(row=current_row+i, column=col_idx, value=pkg['price']).number_format = '#,##0'
                ws.cell(row=current_row+i, column=col_idx+1, value=pkg['gb'])
                ws.cell(row=current_row+i, column=col_idx+2, value=pkg['days'])

                c_yield = ws.cell(row=current_row+i, column=col_idx+3, value=pkg['yield'])
                c_yield.number_format = '#,##0'
                yield_cells.append(c_yield.coordinate) # Simpan posisi sel untuk heatmap warna

                # Highlight best deal (Red dashed border)
                if pkg['yield'] == min_yield_in_row and pkg['yield'] > 0:
                    for offset in range(4): ws.cell(row=current_row+i, column=col_idx+offset).border = border_red_dashed

            col_idx += 4

    current_row += max_rows

# --- 3. APPLY CONDITIONAL FORMATTING (HEATMAP YIELD) ---
# Format warna Hijau (murah) - Kuning (standar) - Merah (mahal)
color_scale = ColorScaleRule(start_type='min', start_color='63BE7B', mid_type='percentile', mid_value=50, mid_color='FFEB84', end_type='max', end_color='F8696B')
if yield_cells:
    # Buat range sel contoh: "E3:E15, I3:I15, dst"
    ws.conditional_formatting.add(f"E3:Z{current_row}", color_scale)

# Auto-adjust column width
for col_idx in range(1, ws.max_column + 1):
    column_letter = get_column_letter(col_idx)
    max_length = 0
    for cell in ws[column_letter]:
        # Abaikan tipe MergedCell agar tidak error
        if type(cell).__name__ == 'MergedCell':
            continue

        if cell.value:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass

    adjusted_width = (max_length + 2)
    ws.column_dimensions[column_letter].width = adjusted_width

ws.column_dimensions['A'].width = 15 # Fix lebar kolom Kategori

# Simpan File
filename = "Dashboard_Input_Harga.xlsx"
wb.save(filename)
files.download(filename)
print(f"Bim salabim! File {filename} siap diekspor ke Antigravity.")

import zipfile
import cv2
import numpy as np
from pathlib import Path
from tqdm import tqdm
from PIL import Image
from google.colab import files
import shutil
import json
import time
import pandas as pd
from IPython.display import display
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.utils import get_column_letter
import math

# Asumsi `genai`, `client`, `MODEL`, `PROMPT`, dan `get_new_gemini_client`
# telah didefinisikan di sel sebelumnya dan dapat diakses secara global.
# Variabel `API_KEYS` dan `api_key_iterator` juga diasumsikan sudah ada
# dan dikelola oleh `get_new_gemini_client`.

def run_data_extraction_pipeline():
    global client # Declare client as global here
    print("🚀 Memulai pipeline ekstraksi data...")

    # 1. Choose File (Upload Zip)
    print("\n📦 Langkah 1: Mengunggah file zip yang berisi gambar...")
    uploaded = files.upload()
    if not uploaded:
        print("❌ Tidak ada file yang diunggah. Pipeline dibatalkan.")
        return

    zip_name = list(uploaded.keys())[0]
    print(f"✅ File '{zip_name}' berhasil diunggah.")

    # 2. Extract Zip
    print("\n🔍 Langkah 2: Mengekstrak gambar dari file zip...")
    extract_folder = Path("/content/images")
    # Hapus folder sebelumnya jika ada untuk memastikan hanya file terbaru yang diproses
    if extract_folder.exists() and extract_folder.is_dir():
        shutil.rmtree(extract_folder)
    extract_folder.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_name, "r") as zip_ref:
        zip_ref.extractall(extract_folder)

    image_files = []
    for ext in ["*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG"]:
        image_files.extend(extract_folder.rglob(ext))
    image_files = sorted(image_files)

    if not image_files:
        print("❌ Tidak ada gambar yang ditemukan dalam file zip. Pipeline dibatalkan.")
        return

    print(f"✅ Ditemukan {len(image_files)} gambar setelah ekstraksi.")

    # 3. Data Preprocessing
    print("\n⚙️ Langkah 3: Melakukan preprocessing pada gambar...")
    processed_folder = Path("/content/preprocessed")
    processed_folder.mkdir(exist_ok=True)
    processed_images = []

    for img_path in tqdm(image_files, desc="Memproses gambar"):
        img = cv2.imread(str(img_path))
        if img is None:
            print(f"⚠️ Gagal membaca gambar: {img_path.name}. Melewatkan gambar ini.")
            continue

        h, w = img.shape[:2]
        if w > 1800:
            scale = 1800 / w
            img = cv2.resize(img, (1800, int(h * scale)))

        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        l = clahe.apply(l)
        lab = cv2.merge((l, a, b))
        img = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

        kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
        img = cv2.filter2D(img, -1, kernel)

        save_path = processed_folder / img_path.name
        cv2.imwrite(str(save_path), img)
        processed_images.append(save_path)

    print("✅ Preprocessing selesai.")

    # 4. Extract Data using Gemini
    print("\n🤖 Langkah 4: Mengekstrak data dari gambar menggunakan Gemini AI...")
    all_packages = []
    max_retries = 6  # Jumlah percobaan ulang untuk panggilan API

    for image_path in tqdm(processed_images, desc="Ekstraksi data AI"):
        img_pil = Image.open(image_path)  # Gambar PIL untuk Gemini

        for attempt in range(max_retries):
            try:
                response = client.models.generate_content(
                    model=MODEL,
                    contents=[PROMPT, img_pil]
                )

                text = response.text.strip()
                text = text.replace("```json", "").replace("```", "")
                data = json.loads(text)
                all_packages.extend(data)
                break  # Keluar dari loop retry jika berhasil

            except Exception as e:
                error_msg = str(e)
                if "503" in error_msg or "UNAVAILABLE" in error_msg or "429" in error_msg:
                    print(f"⚠️ API Limit / Server Sibuk (Percobaan {attempt+1}/{max_retries} untuk {image_path.name}). Mencoba API Key baru...")
                    client = get_new_gemini_client()
                    time.sleep(2)  # Beri jeda agar client baru stabil
                else:
                    print(f"❌ Gagal Parse JSON atau Error Lainnya untuk {image_path.name}: {error_msg}")
                    if 'response' in locals() and hasattr(response, 'text'):
                        print(response.text)
                    break  # Hentikan percobaan ulang untuk gambar ini jika error bukan karena kuota/server sibuk

    print(f"✅ Ekstraksi AI selesai. Total {len(all_packages)} paket ditemukan.")

    if not all_packages:
        print("⚠️ Tidak ada paket yang berhasil diekstrak. Tidak dapat membuat laporan.")
        return

    # 5. Generate Excel Report
    print("\n📊 Langkah 5: Membuat laporan Excel...")
    df_clean = pd.DataFrame(all_packages)

    # Normalisasi Provider
    provider_mapping = {
        'INDOSAT': 'IM3', 'THREE': '3ID', 'TELKOMSEL': 'TSEL',
        'SMARTFREN': 'SF', 'XL': 'XL', 'AXIS': 'AXIS'
    }
    df_clean['provider'] = df_clean['provider'].astype(str).str.upper().map(provider_mapping).fillna(df_clean['provider'].astype(str).str.upper())

    # Konversi tipe data dan kalkulasi Yield
    df_clean['price'] = pd.to_numeric(df_clean['price'], errors='coerce')
    df_clean['gb'] = pd.to_numeric(df_clean['gb'], errors='coerce')
    df_clean['days'] = pd.to_numeric(df_clean['days'], errors='coerce')
    df_clean = df_clean.dropna(subset=['price', 'gb', 'days'])  # Buang data tidak lengkap

    df_clean['yield'] = (df_clean['price'] / df_clean['gb']).apply(lambda x: math.ceil(x) if x != np.inf else 0)

    # Fungsi Kategorisasi
    def categorize(d, p):
        if d <= 2: return "SACHET 1D-2D"
        elif d == 3: return "SACHET 3D"
        elif d <= 5: return "SACHET 5D"
        elif d <= 7: return "SACHET 7D"
        elif d <= 15: return "SACHET 10D-15D"
        elif d >= 28 and p <= 50000: return "MONTHLY 30-50K"
        elif d >= 28 and p > 50000: return "MONTHLY > 50K"
        else: return "OTHER"

    df_clean['category'] = df_clean.apply(lambda row: categorize(row['days'], row['price']), axis=1)

    # Sortir data dari yang termurah per kategori
    df_clean = df_clean.sort_values(by=['category', 'provider', 'price'])

    # --- 2. EXCEL GENERATION (OPENPYXL) ---
    wb = Workbook()
    ws = wb.active
    ws.title = "Rekap Harga Automasi"

    HEADER_COLORS = {"IM3": "FFC000", "3ID": "FF00FF", "TSEL": "FF0000", "XL": "0070C0", "AXIS": "7030A0", "SF": "FF00FF"}
    providers_order = ["IM3", "3ID", "TSEL", "XL", "AXIS", "SF"]
    categories_order = ["SACHET 1D-2D", "SACHET 3D", "SACHET 5D", "SACHET 7D", "SACHET 10D-15D", "MONTHLY 30-50K", "MONTHLY > 50K"]

    font_bold_white = Font(bold=True, color="FFFFFF")
    align_center = Alignment(horizontal="center", vertical="center")
    border_thin = Border(left=Side(style='thin'), right=Side(style='thin'), top=Side(style='thin'), bottom=Side(style='thin'))
    border_red_dashed = Border(left=Side(style='mediumDashed', color='FF0000'), right=Side(style='mediumDashed', color='FF0000'),
                               top=Side(style='mediumDashed', color='FF0000'), bottom=Side(style='mediumDashed', color='FF0000'))

    # Generate Header
    col_start = 2
    for prov in providers_order:
        ws.merge_cells(start_row=1, start_column=col_start, end_row=1, end_column=col_start + 3)
        c = ws.cell(row=1, column=col_start, value=prov)
        c.fill, c.font, c.alignment, c.border = PatternFill(start_color=HEADER_COLORS.get(prov, "808080"), fill_type="solid"), font_bold_white, align_center, border_thin

        for i, sh in enumerate(["Price", "GB", "Days", "Yield"]):
            c_sub = ws.cell(row=2, column=col_start + i, value=sh)
            c_sub.fill = PatternFill(start_color="FFD966", fill_type="solid") if sh == "Yield" else PatternFill(start_color="D9D9D9", fill_type="solid")
            c_sub.font, c_sub.alignment, c_sub.border = Font(bold=True), align_center, border_thin
        col_start += 4

    # Generate Body Data Horizontal
    current_row = 3
    yield_cells = []  # Untuk menyimpan koordinat sel yang akan diberi warna heatmap

    for cat in categories_order:
        cat_df = df_clean[df_clean['category'] == cat]
        if cat_df.empty: continue

        prov_data = {prov: cat_df[cat_df['provider'] == prov].to_dict('records') for prov in providers_order}
        max_rows = max([len(v) for v in prov_data.values()] + [1])

        ws.merge_cells(start_row=current_row, start_column=1, end_row=current_row + max_rows - 1, end_column=1)
        c_cat = ws.cell(row=current_row, column=1, value=cat)
        c_cat.alignment, c_cat.border = Alignment(vertical="center", horizontal="center", wrap_text=True), border_thin

        for i in range(max_rows):
            col_idx = 2

            # Cari yield terkecil di baris ini untuk "Best Offer Red Dashed Box"
            row_yields = []
            for prov in providers_order:
                if i < len(prov_data[prov]): row_yields.append(prov_data[prov][i]['yield'])
            min_yield_in_row = min(row_yields) if row_yields else None

            for prov in providers_order:
                for offset in range(4):  # Set border abu-abu default untuk semua sel (meskipun kosong)
                    ws.cell(row=current_row + i, column=col_idx + offset).border = border_thin

                if i < len(prov_data[prov]):
                    pkg = prov_data[prov][i]

                    # Format Harga & Yield (Rp / Koma Ribuan)
                    ws.cell(row=current_row + i, column=col_idx, value=pkg['price']).number_format = '#,##0'
                    ws.cell(row=current_row + i, column=col_idx + 1, value=pkg['gb'])
                    ws.cell(row=current_row + i, column=col_idx + 2, value=pkg['days'])

                    c_yield = ws.cell(row=current_row + i, column=col_idx + 3, value=pkg['yield'])
                    c_yield.number_format = '#,##0'
                    yield_cells.append(c_yield.coordinate)  # Simpan posisi sel untuk heatmap warna

                    # Highlight best deal (Red dashed border)
                    if pkg['yield'] == min_yield_in_row and pkg['yield'] > 0:
                        for offset in range(4): ws.cell(row=current_row + i, column=col_idx + offset).border = border_red_dashed

                col_idx += 4
        current_row += max_rows

    # --- 3. APPLY CONDITIONAL FORMATTING (HEATMAP YIELD) ---
    # Format warna Hijau (murah) - Kuning (standar) - Merah (mahal)
    color_scale = ColorScaleRule(start_type='min', start_color='63BE7B', mid_type='percentile', mid_value=50, mid_color='FFEB84', end_type='max', end_color='F8696B')
    if yield_cells:
        # Buat range sel contoh: "E3:E15, I3:I15, dst"
        ws.conditional_formatting.add(f"E3:Z{current_row}", color_scale)

    # Auto-adjust column width
    for col_idx in range(1, ws.max_column + 1):
        column_letter = get_column_letter(col_idx)
        max_length = 0
        for cell in ws[column_letter]:
            # Abaikan tipe MergedCell agar tidak error
            if type(cell).__name__ == 'MergedCell':
                continue

            if cell.value:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass

        adjusted_width = (max_length + 2)
        ws.column_dimensions[column_letter].width = adjusted_width

    ws.column_dimensions['A'].width = 15  # Fix lebar kolom Kategori

    # Simpan File
    filename = "Dashboard_Input_Harga.xlsx"
    wb.save(filename)
    files.download(filename)
    print(f"✅ Laporan '{filename}' berhasil dibuat dan siap diunduh!")

# Panggil fungsi pipeline untuk memulai proses
run_data_extraction_pipeline()